version: "2.4"
services:
  database:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    volumes:
      - .:/code
    ports:
      - "3306:3306"
    networks:
      - database_net
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=password
      interval: 5s
      timeout: 45s
      retries: 40

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - backend/local.env
    environment:
      - IS_MIGRATION=true
      - DATABASE_URL=mysql://root:password@database:3306/test
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    networks:
      - database_net

  frontend:
    build: ./frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "5173:5173"
    network_mode: host

volumes:
  common:


networks:
  database_net:
