-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 18:44:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'password';
flush privileges;
